### ISSUE TITLE
Temporarily active suspended users when assigning roles

### ISSUE THREAD

**Issue by eligosfx** [strongdm/accessbot#110]
We need to create workflow automation for suspended users.
Users from the suspended group will send a request over the slack channel and the bot will approve however one step doesn't exist. Once the suspended user will get temporary access he has to move again to the suspended group.

**Comment by camposer** [comment]
Automatically activate and suspend **tagged users** when granting them temporal permissions. It's very important to distinguish users that are going to be treated this way, because otherwise you might end-up suspending sensible users, like an admin or a team lead!

**Comment by camposer** [comment]
Please refer to the image below for the implementation details:

![image](https://user-images.githubusercontent.com/313803/133443723-0f7d81db-3aec-454e-8c65-e84cfbc6fa91.png)

**Comment by camposer** [comment]
Let's better make the variable `SDM_AUTO_SUSPEND_USER_TAG`
