### ISSUE TITLE
Conceal not working as expected (?)

### ISSUE THREAD

**Issue by mrxkon** [strongdm/accessbot#192]
**Describe the bug**
In #173 a new `SDM_CONCEAL_RESOURCE_TAG` was introduced for the purposes of #168 . Setting up the new variable doesn't seem to be working as expected though, the resources are still being listed when `show vailable resources` is run.

**Screenshots**
Variable is set in `docker-compose.yml` to use the `accessbot-conceal` tag.
![image](https://user-images.githubusercontent.com/22611066/146543387-2663f1e8-9cff-4ebd-a006-2ea663c46006.png)

`accessbot-conceal=true` is set on the given resource.
![image](https://user-images.githubusercontent.com/22611066/146543467-433c9eac-0562-4118-9d90-8ff0be2e84f7.png)

`show available resources` lists the server which is not the expected behavior.
![image](https://user-images.githubusercontent.com/22611066/146543349-1a152388-6a92-40a9-a19d-9445eefee27b.png)

**Additional context**
Not sure if I'm missing anything here and I've set up the accessbot from scratch as well so it's unlikely that I'm using a wrong version, but feel free to tell me how I could provide more info to help :) .

**Comment by mrxkon** [comment]
Closing this, apparently the docker image didn't update properly yesterday so it was stuck on an older version. Pruning everything & re-downloading the image from scratch worked like a charm :) .

**Comment by camposer** [comment]
Happy to read that it's working as expected
