### ISSUE TITLE
Auto approve groups not working as expected (?)

### ISSUE THREAD

**Issue by mrxkon** [strongdm/accessbot#193]
**Describe the bug**
In #187 2 new variables where introduced for allowing auto-approval to resources by groups for #167.

**Expected behavior**
The access to the resources should've been automatically granted.

**Screenshots**
The user has the tag `groups=accessbot-allow`
![image](https://user-images.githubusercontent.com/22611066/146551118-0c0a8349-87ad-4476-a842-15a668165c72.png)

`docker-compose.yaml` has SDM_GROUPS_TAG & SDM_AUTO_APPROVE_GROUPS_TAG set
![image](https://user-images.githubusercontent.com/22611066/146550602-fc00ad6c-8b43-45cb-852b-bcad09fb0ba6.png)

The resource has `accessbot-group=accessbot-allow` so any user with the groups=accessbot-allow should be granted access.
![image](https://user-images.githubusercontent.com/22611066/146550733-324a793e-d8cb-4703-b42e-8f9c04a77f0d.png)

AccessBot still asks Admins for authorization for this resource (in this case my user has the group/tag but also an admin so everything is in 1 screenshot :) ).
![image](https://user-images.githubusercontent.com/22611066/146550995-6d1c6c71-7a50-4aab-93a2-aab138f57b66.png)

**Additional context**
Using the latest code from github & docker:latest , not sure if any other variables need to be used in conjunction with this.

**Comment by camposer** [comment]
Happy to read that it's working as expected
