### ISSUE TITLE
SDM_COMMANDS_ENABLED - Code doesn't match Documentation

### ISSUE THREAD

**Issue by stevekoskie** [strongdm/accessbot#194]
From the Documents:
SDM_COMMANDS_ENABLED. AccessBot commands to be enabled. Default = access_resources assign_role show_resources show_roles

The code in the config.py looks for "access_resource" not "access_resources". However, since show_resources is plural and access_resource is singular I wasn't sure which way you ultimately want it.

**Comment by camposer** [comment]
Thank you very much @stevekoskie for noticing the issue and letting us know. We just updated the docs, the correct setup would be:

```
SDM_COMMANDS_ENABLED. AccessBot commands to be enabled. Default = access_resource assign_role show_resources show_roles approve
```

In case you want to take a look at the code: https://github.com/strongdm/accessbot/blob/main/config.py#L4
