### ISSUE TITLE
Change acknowledgement message when using SDM_ADMINS_CHANNEL

### ISSUE THREAD

**Issue by wrenhunter** [strongdm/accessbot#196]
**Is your feature request related to a problem? Please describe.**
When using SDM_ADMINS_CHANNEL, to allow anyone in a given channel to approve requests, users continue to see a message like:

```
Thanks @username, that is a valid request. Let me check with the team admins: @Admin2 @Admin2 
```

This is misleading, because the request does not require approval from those specific users (and they may well not be in the configured channel).

**Describe the solution you'd like**
The bot should check to see if SDM_ADMINS_CHANNEL is set, and if so, the message should read e.g.

```
Thanks @username, that is a valid request. I have created a request for approval in the channel #CHANNEL_NAME 
```

**Comment by camposer** [comment]
Because the admin channel name may be not exposed, we'll change the message to:
```
Thanks @username, that is a valid request. I have created a request for approval in the configured admin channel 
```
