### ISSUE TITLE
Add Slackbot shortened commands

### ISSUE THREAD

**Issue by evan-scott** [strongdm/accessbot#197]
**Is your feature request related to a problem? Please describe.**
TCEU wants to type 'ar [resource]' rather than 'access request [resource]', partially because it's a lot to type and partially because they're envisioning this in a production incident scenario where every second counts.

**Describe the solution you'd like**
Allow accessbot to understand both 'access request' and 'ar' as suitable commands, along with any others that can be shortened.

**Describe alternatives you've considered**
N/A, open to suggestions though.

**Additional context**
https://app.gong.io/call?id=8746579382246779781&highlights=%5B%7B%22type%22%3A%22SHARE%22%2C%22from%22%3A1057%2C%22to%22%3A1791%7D%5D

**IMPORTANT**: Remember to select a label and project - I can't :(

**Comment by camposer** [comment]
Allow the user to configure short commands via configuration:
```
COMMAND_ALIASES = {
  "show_resources": "sr",
  "access_resource": "ar",
  "assign_role": None,
  "show_roles": None,
  "approve": None
}
```

**Comment by camposer** [comment]
We ended up adding the alises to the COMMANDS_ENABLED variable. I usually go with:
```
SDM_COMMANDS_ENABLED="access_resource:ar assign_role show_resources:sr show_roles approve:y deny"
```

So the alias for `show available resources` is `ar`
