### ISSUE TITLE
Add failsafe option for after-hours support

### ISSUE THREAD

**Issue by wrenhunter** [strongdm/accessbot#2]
**Is your feature request related to a problem? Please describe.**
Imagine a system-wide issue occurs at night, when an on-call Engineer needs access to an SDM resource to solve a system-down problem. It might be good to have a "failsafe" option, where any user gets automatic access during a defined window.

**Describe the solution you'd like**
Add a failsafe option, as a binary option. If TRUE, a user access request will be auto-approved if it occurs during a defined time window.

**Describe alternatives you've considered**
Might want to limit this to certain users, perhaps defined in a list as "on-call users". User would need to be in that list, and match the time window, to get auto-approval.

Another option could be an "on-call" admin -- ping different folks for approval depending on time of day.

**Additional context**
Arguably, this reduces security. But users still must a) belong to the Slack workspace, b) have access to the channel, and c) all grants and activities are audited in SDM.

**Comment by camposer** [comment]
Apparently it was already solved. Closing the ticket because it's stale.
