### ISSUE TITLE
AccessBot in 2 channels

### ISSUE THREAD

**Issue by mdube667** [strongdm/accessbot#203]
**Is your feature request related to a problem? Please describe.**
Customer would like to have a single instance of accessbot responding in 2 different channels to 2 different set of admins responsible for 2 different set of resources.

**Describe the solution you'd like**
AccessBot answering to 2 channels

**Describe alternatives you've considered**
Right now, you can have the bot in 2 channels but it always replies in the same channel

**Comment by camposer** [comment]
It'd need a major refactor.
