### ISSUE TITLE
Allow users to request duration to override SDM_GRANT_TIMEOUT

### ISSUE THREAD

**Issue by jeffalloy** [strongdm/accessbot#207]
**Describe the solution you'd like**
Currently the only way for users to request access longer than the default time configured via the environment variable one has to go to the SDM console and do it that way

What would be ideal is to have request duration in the request workflow command such as:

```shell
access to resource duration

access to 'prod db' 120m
```

**Describe alternatives you've considered**
Not using AccessBot and continue using ad-hoc requests via a Slack Workflow

**Additional context**

**IMPORTANT**: Remember to select a label and project

**Comment by camposer** [comment]
In order to differentiate from "access to resource <reason>" we'll use a special flag:
```
access to resource --duration 2m
```

**Comment by camposer** [comment]
We should treat the duration flag as following:
```
access to resource --duration 60 => Grants access for 60 minutes
access to resource --duration 60m => Grants access for 60 minutes
access to resource --duration 1h => Grants access for 1 hour
```

About the possible input types, check [here](https://stackoverflow.com/a/3096934)
