### ISSUE TITLE
Show Available Roles Output like Resources

### ISSUE THREAD

**Issue by Crystalirlandez** [strongdm/accessbot#214]
**Is your feature request related to a problem? Please describe.**
Easier way for team members to request temp access from different roles 

**Describe the solution you'd like**
Be able to view available roles in an output like we can with resource 

**Describe alternatives you've considered**
Nothing, the current show available roles does not satisfy what the customer is trying to use accessbot for

**Additional context**
Direct from the customer: 

Currently, it's possible to curate the "show available resources" output by using this variable in the docker config file:
SDM_ALLOW_RESOURCE_TAG=accessbot-show

However, it doesn't look possible to do the same thing with "show available roles". It would be great if there was a similar feature for roles so that I could trim down that output as well. Something like this?
SDM_ALLOW_ROLE_TAG=accessbot-show

**IMPORTANT**: Remember to select a label and project

**Comment by corey-strongdm** [comment]
Hi @camposer ! Curious if there is an update on this that I can provide to the customer? Thanks!

**Comment by camposer** [comment]
Hi @corey-strongdm 

It's the next item in the backlog :-)

We should have something for the customer mid next week.

**Comment by corey-strongdm** [comment]
thanks, Rodo! that's great :)
