### ISSUE TITLE
Allow upper-case "Yes" to approve access request

### ISSUE THREAD

**Issue by iancoxey** [strongdm/accessbot#219]
**Is your feature request related to a problem? Please describe.**
It is frustrating to need to correct the capitalization in an access approval message within slack.  Mobile phones typically autocorrect the first letter of a message to a capital - accessbot currently does not accept that capital letter.

**Describe the solution you'd like**
Allow both upper and lower-case Y in approval messages. ex: "Yes xxxx" and "yes xxxx"

**Describe alternatives you've considered**
Not applicable

**Additional context**
Copy/paste from the customer ticket: 

> If I want to approve request 8HMM from my phone, I type "yes 8HMM", but my phone autocorrects the "yes" to "Yes", and accessbot replies "Invalid access request id = Yes 8HMM".  I'm able to get around it by undoing the autocorrect, but it's a workaround that I have to make sure all of the users are aware of - it seems like maybe something's off with the piece that extracts the request ID, because clearly it interpreted the uppercase "Yes" as a command, but then just didn't know how to get the request ID out of it.

**Comment by camposer** [comment]
I think that we should ignore cases for all AB commands! For example:

```
AccES to DOCKER-Postgres
access TO docker-POSTGRES
````

IMPORTANT: The system is case insensitive (like Windows) when detecting duplicated resource names.
