### ISSUE TITLE
Allow users to request time extension for a temporary access grant 

### ISSUE THREAD

**Issue by samueljones2212** [strongdm/accessbot#221]
**Is your feature request related to a problem? Please describe.**
Currently a user must wait for their existing temporary access grant to expire before requesting an additional time grant for that resource. That means their access may be cut off mid-flow and they could potentially have to stop work for a period of time (potentially during an incident) while they re-submit a request and await approval. 

**Describe the solution you'd like**
Allow users to request temporary access to resources they've already been granted access to. The new grant could override the previous one (i.e. I'm 30minutes into my 60mins of access, I know I'll need at least another hour and I have a few mins spare - I can request a new grant of 90mins and this would be approved and replace my existing grant, rather than adding on to it). 

**Describe alternatives you've considered**
Adding the new request onto the back of the existing request, so If I get another 60mins approved, it starts from the time my current access ends. That feels less intuitive though.

**Comment by camposer** [comment]
We need to explore if it's possible to update a temporal grant, otherwise we would need to revoke and create a new one, which might drop the ongoing session.

**Comment by vassalo** [comment]
Hey, guys. After some digging, we don't think it is possible to update an existing access grant. The only solution we can think is to revoke the existing grant and create a new one. But if we do that, the session of the current grant would be closed and the user would need to reconnect to the resource after the new grant has been created. How does this sounds to you?

If that approach sounds good for you, we have to think about the grant approval. Should the new access grant be automatically approved for a resource that the user already has access to, or the access grant should be manually approved by an admin?

**Comment by samueljones2212** [comment]
Here are my thoughts but I'll also discuss with a couple of customers to see what they think:

- I think revoking the existing grant and creating a new one is ok if we can warn the user that they have an existing grant and if they proceed, it will be terminated and they'll need to reconnect to the resource(s) once the new grant is approved
- The new grant should require the same level of approval as the previous one. If the initial request required manual approval, the new grant should require the same

**Comment by camposer** [comment]
We'll keep the issue open until we hear back from you @samueljones2212

**Comment by glaracuente** [comment]
As a customer who is hoping for this feature to be implemented, I completely agree with @samueljones2212 's thoughts.

Revoking and creating a new grant, therefore causing existing connections to drop sounds reasonable. 

And the new grant should require a fresh approval, since a bad actor could manipulate the system if the extension was auto-approved. 

In order to avoid confusion about the fact that the grant isn't necessarily "extended", but "re-created" to include an end time farther in the future, maybe the name of the flag for this should attempt to make that obvious. This is an implementation detail, but just a suggestion. Not even sure what a good name would be, but something like "extend" would be misleading.

**Comment by vassalo** [comment]
Okay, so here's the proposed solution:

We'll add a new environment variable `SDM_ALLOW_ACCESS_REQUEST_RENEWAL`, disabled by default.

When this variable is `true` and a user makes a new access request for a resource they already have access to, a new request will be created and will follow the expected approval flow.

Once the request is approved, the previous/current grant will be revoked and a new one will be created.

In the "access granted" message the bot will say that the previous grant was revoked, a new one was created and the user might need to reconnect to that resource.

**Comment by glaracuente** [comment]
that sounds amazing, thank you!
