### ISSUE TITLE
When using SDM_ADMIN_CHANNEL, anyone in that channel can run admin commands

### ISSUE THREAD

**Issue by wrenhunter** [strongdm/accessbot#222]
**Is your feature request related to a problem? Please describe.**
In our demo environments, we usually use SDM_ADMIN_CHANNEL to simplify. It would be nice if any user in that channel could run e.g. `status`.

I think this would also be useful for customers, since one of the purposes of this feature is that different folks may be "admins" on different shifts.

**Describe the solution you'd like**
When using SDM_ADMIN_CHANNEL, anyone in that channel can run admin and config commands, e.g. status.

**Describe alternatives you've considered**
Perhaps a new flag like ADMIN_CHANNEL_ELEVATE, that makes this optional when using SDM_ADMIN_CHANNEL.

**Comment by camposer** [comment]
Every time a user gets added to the channel, the admin must restart the Bot. @vassalo @gaabrieljesuss please add details here.
