### ISSUE TITLE
Timeouts or invalid request IDs happen intermittently

### ISSUE THREAD

**Issue by jeffalloy** [strongdm/accessbot#223]
**Describe the bug**
Sometimes a request gets sent and the message is visually seen in the request channel however when approving or rejecting the request the request id is nowhere to be found

This is well below the SDM ADMIN TIMEOUT as well

**To Reproduce**
1. Ask for a resource request
2. Sometimes request ID is invalid

**Expected behavior**
Request is valid and access is granted

**Screenshots**

<img width="1391" alt="Screen Shot 2022-04-11 at 11 26 11 AM" src="https://user-images.githubusercontent.com/73024439/162773800-dbcc43ac-c112-441b-9e8e-3f15efcede68.png">
<img width="1118" alt="Screen Shot 2022-04-11 at 11 26 00 AM" src="https://user-images.githubusercontent.com/73024439/162773802-4b9e9b9f-db39-4d85-827c-34c12124d525.png">

<img width="369" alt="Screen Shot 2022-04-11 at 11 26 22 AM" src="https://user-images.githubusercontent.com/73024439/162773797-b6cce8fd-7398-4648-845a-20228720b4f0.png">

**Comment by camposer** [comment]
Hi @jeffalloy 

Thanks for sharing this. Very interesting issue, looks like the request is timing out before someone can approve it. 

In the example you've shared above, **chuan** is entering a wrong id (the id is case sensitive) and then failing when **lee** enters it properly. 

The default timeout for approving an access request is very low, 30sec. Could you please try to increase it, see [here](https://github.com/strongdm/accessbot/blob/main/docs/CONFIGURE_ACCESSBOT.md?plain=1#L28)

Thank you,

**Comment by jeffalloy** [comment]
Hi @camposer , we increased the timeout to 3600 seconds (1 hour) and sometimes it still fails.

**Comment by jeffalloy** [comment]
> Interesting @jeffalloy
> 
> The only use case I can think of:
> 
>     * The request expired
> 
>     * The request was already approved
> 
>     * The bot was restarted - access requests are stored in memory
> 
> 
> Could you please confirm if any of the points above applies? If not, please send your logs and a reference to this issue to: `support at strongdm.com`

Hi @camposer when it happens again, I can send logs and reference to this issue and will close out this for now.

**Comment by camposer** [comment]
@lslaslo there's a plan for persisting access requests on disk. You'd need to mount a volume with EFS or similar, but it could make the trick. I'll communicate your request to the team.

**Comment by lslaslo** [comment]
@camposer did a persistent storage option ever happen?

**Comment by camposer** [comment]
Hi @lslaslo

Thanks for reaching out! Yes, it was implemented. Please take a look at the [docs](https://github.com/strongdm/accessbot/#using-disposable-containers)
