### ISSUE TITLE
Slack-native app versus a channel. 

### ISSUE THREAD

**Issue by grioghar** [strongdm/accessbot#245]
**Is your feature request related to a problem? Please describe.**
Slack App

**Describe the solution you'd like**
Build a Slack-native helper app that allows for actions

**Describe alternatives you've considered**
Customer-requested

**Additional context**
Customer was interested in a 'Help' type button. 

**IMPORTANT**: Remember to select a label and project
Done.

**Comment by camposer** [comment]
This is going to be addressed in the Access Workflows project
