### ISSUE TITLE
Add health check endpoint

### ISSUE THREAD

**Issue by wallrony** [strongdm/accessbot#249]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to know if AccessBot is running ok or not. It's ideally got via a healthcheck endpoint.

**Describe the solution you'd like**
It would be nice to have a healthcheck endpoint using the Errbot Webserver (instead of using a Flask instance).

**Comment by acesdm** [comment]
Just an FYI, @wallrony and @vassalo we have a new ticket in from Alloy saying their healthchecks are failing (Accessbot Failing Healthchecks in ECS), and it looks like this is the very thing you created this issue for.

https://strongdm.zendesk.com/agent/tickets/5362

**Comment by wallrony** [comment]
Hey @acesdm! We pushed a commit with this feature in the [staging branch](https://github.com/strongdm/accessbot/tree/staging), which is acting kinda as a pre-release branch while Rodo's out. So if you want to take a look at it, please go ahead and give some feedback, but keep in mind that something might change when Rodo comes back.
