### ISSUE TITLE
Docker image for Access Form

### ISSUE THREAD

**Issue by perezjc** [strongdm/accessbot#253]
**Is your feature request related to a problem? Please describe.**
From the customer "We run all our applications on containers and would prefer to do the same thing here"

**Describe the solution you'd like**
A docker image for access form 

**Describe alternatives you've considered**
manual installation

**Comment by beckler** [comment]
dont know if this will help you, but it looks like they publish an image here: https://gallery.ecr.aws/strongdm/accessbot
