### ISSUE TITLE
Allow SDM_ADMIN_CHANNEL to be a slack-connect channel shared with a 3rd party.

### ISSUE THREAD

**Issue by tonylokko** [strongdm/accessbot#260]
**Is your feature request related to a problem? Please describe.**

Currently you can point accessbot to a channel for approvals to happen. This is set by the environment variable SDM_ADMINS_CHANNEL 
When setting this to a local channel to the workspace there are no errors. We have a client who has some requirements to have a 3rd party manage approvals for some infrastucture. This could be done by adding them to the admins channel and sharing that channel via slack.
Currently if you do this the accessbot cannot find the channel. 

example error logs
ile "/opt/conda/lib/python3.9/site-packages/errbot/core.py", line 546, in _execute_and_send
    for reply in replies:
  File "plugins/sdm/accessbot.py", line 102, in access_resource
    yield from self.get_resource_grant_helper().request_access(message, resource_name, flags=flags)
  File "/errbot/plugins/sdm/lib/helper/base_grant_helper.py", line 27, in request_access
    yield from self.__grant_access(message, sdm_resource, sdm_account, execution_id, request_id, flags)
  File "/errbot/plugins/sdm/lib/helper/base_grant_helper.py", line 72, in __grant_access
    yield from self.__request_manual_approval(message, sdm_object, sdm_account, execution_id, request_id, sender_nick, flags)
  File "/errbot/plugins/sdm/lib/helper/base_grant_helper.py", line 96, in __request_manual_approval
    self.__check_administration_availability()
  File "/errbot/plugins/sdm/lib/helper/base_grant_helper.py", line 156, in __check_administration_availability
    raise Exception("An Admin Channel was defined but it's unreachable.")
Exception: An Admin Channel was defined but it's unreachable.
"

**Describe the solution you'd like**

Allow the sdm_admins_channel have that check and post use the conversations api. https://api.slack.com/apis/connect

**Describe alternatives you've considered**
inviting the 3rd party to main slack workspace rather than use slack connect.

**Comment by wallrony** [comment]
Hi @tonylokko!
We couldn't reproduce this error. Please update your AccessBot version and try again. Recently we fixed a bug related to configuring the admins channel, and maybe that was the problem.
