### ISSUE TITLE
Fargate Instructions Update Request

### ISSUE THREAD

**Issue by alin-strongdm** [strongdm/accessbot#282]
**Describe the bug**
The container goes into “unable to mount NFS timeout” and cluster never comes up if you don't follow the suggested steps below. This should be added towards the start of the guide when getting an ECS cluster up and running and added into [step 4](https://github.com/strongdm/accessbot/blob/main/docs/deploy/FARGATE.md).

**Steps to add**
1. create ec2 security group as any name, can use ‘accessbot-ecs-cluster-sg’
2. confirm outbound has all tcp or just NFS -> 2409 port
3. use this security group(‘accessbot-ecs-cluster-sg’) when creating the ECS cluster
4. in EFS security group, add an inbound rule as the above accessbot-ecs-cluster-sg security group ID being the source, NFS type, port 2409 again

**Expected behavior**
Container should not go into "unable to mount NFS timeout" error

**Comment by camposer** [comment]
I don't think our team has experienced this problem. Not sure if it's a specific error. We'll double check and come back to you.

**Comment by camposer** [comment]
The team has confirmed that the commented steps were not needed in our setup. However, we can definitely add that info to the docs as "optional" steps that might help.
