### ISSUE TITLE
Granular filtering in Accessbot - search for resources that match certain conditions

### ISSUE THREAD

**Issue by corey-strongdm** [strongdm/accessbot#287]
Feature Request for theScore: more granular filtering in Accessbot - Ability to search for specific resources that match certain conditions (Ex.) “show available resources - “US Prod””)
- this will make it easier for search of many resources

**Describe the solution you'd like**
- ability to configure or the "show available resources" command with further conditions

**Comment by camposer** [comment]
Hi @corey-strongdm 

Sorry for the delayed response. This is already supported via the filters flag. Please take a look at [this](https://github.com/strongdm/accessbot/blob/main/README.md?plain=1#L103)

Thanks,
