### ISSUE TITLE
Allow required strings in the Reason field

### ISSUE THREAD

**Issue by iancoxey** [strongdm/accessbot#288]
**Is your feature request related to a problem? Please describe.**
A customer is requesting the ability to require a Jira ticket number in the reason field for requests. This better aligns with their record-keeping as to why an employee was requesting access to certain resources.

**Describe the solution you'd like**
Customer would like the ability to require ticket numbers like this: "DM-3222" or "TIX-1234" in the required reason field.  I believe regex would be the most likely solution, something like: [A-Z]{2,}-\d+ 

**Describe alternatives you've considered**
N/A

**Additional context**
[Add any other context or screenshots about the feature request here.](https://strongdm.zendesk.com/agent/tickets/6386)

**IMPORTANT**: Remember to select a label and project

**Comment by camposer** [comment]
You could make this work with the following setup:
![image](https://user-images.githubusercontent.com/313803/196701652-8134c9ec-f3dd-4241-8acb-a3057ea9cc3a.png)
