### ISSUE TITLE
Provide a helm chart for accessbot

### ISSUE THREAD

**Issue by mdube667** [strongdm/accessbot#290]
**Is your feature request related to a problem? Please describe.**
Customer used the helm chart submitted by another customer. And it's incomplete. I don't have enough Helm knowledge to fix it. The customer(ClickUp) would like us to provide a working Helm Chart for accessbot

https://github.com/strongdm/accessbot/tree/4d3e59128b55ebb23856bbc254c556c2699f9a4d/helm

**Describe the solution you'd like**
Provide a supported and tested helm chart for accessbot

**Describe alternatives you've considered**
Right now the customer is using the docker accessbot image and it works fine. So I wouldn't call this urgent.

**Additional context**
ZD ticket: https://strongdm.zendesk.com/agent/tickets/6326

**Comment by camposer** [comment]
We just updated the docs. Basically the customer needs to provide the SDM and BOT credentials in the `values.yaml` file and then use it when running helm. We did it that way and it worked like a charm.
