### ISSUE TITLE
Linux/arm64 image

### ISSUE THREAD

**Issue by alin-strongdm** [strongdm/accessbot#298]
**Is your feature request related to a problem? Please describe.**
Client has requested an accessbot image supporting the linux/arm64 platform as the current image does not play well with how their environment is setup.

**Describe the solution you'd like**
Provide a linux/arm64 image for deployment

**Describe alternatives you've considered**
N/A

**Additional context**
[ZD Ticket](https://strongdm.zendesk.com/agent/tickets/6493)

**Comment by lia-childers** [comment]
Stackadapt
