### ISSUE TITLE
Accessbot task in ECS fails health checks and restarts frequently

### ISSUE THREAD

**Issue by wrenhunter** [strongdm/accessbot#300]
**Describe the bug**
We have Accessbot deployed under an ECS Service. My team reported frequent "pauses" when running Accessbot commands. I checked deployment logs and see that the container/task for AB restarts frequently, as often as every hour some days.

The error in the ECS deployment log is:

```
service prod-demo-bot-service port 3141 is unhealthy in target-group bot-target-group-prod due to (reason Health checks failed).
```

**To Reproduce**
Deploy Accessbot as a Slack Bolt app inside an ECS Service.

**Expected behavior**
Other services (e.g. Prometheus) on the same ECS cluster run for 60+ days without issue. So should Accessbot.

**Comment by wrenhunter** [comment]
Fantastic, thanks so much!

**Comment by wrenhunter** [comment]
Hi @wallrony I had made a different change (increase health check grace period) that has kept the current Task up for 18 days. So I haven't yet implemented your suggestion, but I have confidence in it, so let's close this out. Thanks!

**Comment by wallrony** [comment]
Thank you @wrenhunter!
