### ISSUE TITLE
Resource Tags

### ISSUE THREAD

**Issue by Calagar30** [strongdm/accessbot#304]
**Is your feature request related to a problem? Please describe.**

The client has requested a feature request about using Accessbot with tags so they can give multiple access to resources by only one command using tags.

**Describe the solution you'd like**

When we using Slackbot for grant temporary access to resource and our user can only request 1 resource at a time. It's quite inconvenient when we need to run on many servers at the same time, such as: Ansible Deploy or Sync between server.

So, can you provide additional feature requesting access to tagged resources or another way?

E.g:
```
- Server 1 - Tag: role=game-server
- Server 2 - Tag: role=game-server
```

And with Slackbot - user can make request: 

`access to resources --filter:tag=game-server --duration 20m --reason "Deploy new App"`

**Describe alternatives you've considered**

N/A

**Comment by camposer** [comment]
Hi @Calagar30 

Currently AB allow users to request multiple resources via roles. You could enter:
```
access to role <role-name>
```

And get temporary grant to all the resources listed in the role. Please validate with the customer if this functionality would solve their problem

**Comment by camposer** [comment]
In case the approvers-channel or admins-channel features are not a good fit for the customer, we'll not move forward, because Product asked us to hold on this request because it's going to be implemented as part of the Access Workflows project.
