### ISSUE TITLE
Tutorial or Video of how to use Kubernetes

### ISSUE THREAD

**Issue by mhintz-clickup** [strongdm/accessbot#317]
**Is your feature request related to a problem? Please describe.**
I am a total NOOB for Kubernetes as there is no reason for me to use it. Therefore, I'd like a video tutorial (or even an actual tutorial) son specific implementations. Whether its using AWS, GCP, or whatever, it would be great to get a step-by-step tutorial on how to do this. The current "tutorial" is run this descriptor file and make a values yaml file. This is assuming the user knows what those things even are along AND implies I have setup things like kubectl and helm on my machine. You may find a security engineer who knows Kubernetes very well but that is a RARE find (I don't know ANY who use Kubernetes and understand it completely).

**Describe the solution you'd like**
A 1 - 2 minute video (something short) just showing me how to do this. Should probably have multiple at least showing how to implement with a cloud provider (AWS, GCP, Azure).

**Describe alternatives you've considered**
I tried setting up myself and even got on a call with StrongDM support and couldn't get it working. I was told eventually there will be a terraform script (or something) that does all this for me. This is how I would approach the solution as I like to make things very easy for end users and using IaaC (Infrastructure as Code) would be optimal for this solution. Likely, one of the developers here can whip something up in a few hours.

**Additional context**
No additional context

**IMPORTANT**: Remember to select a label and project

**Comment by camposer** [comment]
Thanks for reaching out @mhintz-clickup 
I commented this request with Rick - the CSM assigned to your account
He'll reach out with a proper update on this
