### ISSUE TITLE
Would be nice not to have to wait 1 minute for access

### ISSUE THREAD

**Issue by etodd** [strongdm/accessbot#54]
I think the 1 minute delay was added because temporary grants are required to be created in the future, but we recently added a 1 minute grace period, so we should be able to remove the delay on this line now:

https://github.com/strongdm/accessbot/blob/b4401a145ae9a5c84721a2c94f2cd9396f240299/plugins/sdm/lib/access_helper.py#L100

**Comment by camposer** [comment]
Brilliant, thank you very much Evan! I'll add this improvement to our backlog
