### ISSUE TITLE
Every command execution should log who in INFO level

### ISSUE THREAD

**Issue by camposer** [strongdm/accessbot#56]
**Is your feature request related to a problem? Please describe.**
Although one can observe who executed a command in DEBUG level, that information is not present when using the default logging level (INFO). It's fundamental to easily get that information from the logs at all times.

**Describe the solution you'd like**
Include who entered a command in INFO logs.

**Describe alternatives you've considered**
That info can be extracted from `message.frm`

**Comment by wallrony** [comment]
Errbot already do that job in every command/message sent by executing this line (in `process_message` method): https://github.com/errbotio/errbot/blob/master/errbot/core.py#L450

**Comment by camposer** [comment]
This was already done.
