### ISSUE TITLE
Beta resources in org cause `show available` command to fail

### ISSUE THREAD

**Issue by wrenhunter** [strongdm/accessbot#62]
**Describe the bug**
Running `show available resources` for an Org that has beta features can throw this error:

Computer says nooo. See logs for details:
'NoneType' object has no attribute 'name'

I saw this before when AWS Cloud was in beta. Now it's because of the new k8s stuff -- when I removed those resoruces from my org, the command completed fine.

**To Reproduce**
Run Accessbot under an org that has at least one k8s-impersonation resource.

**Expected behavior**
Command works.

This was with latest Accessbot code.

**Comment by camposer** [comment]
After a conversation with Ulderico, I realized that the Python SDK is auto-generated and released. I'll add the option "--upgrade" to pip on the docker file, to ensure we always use the latest packages.
