### ISSUE TITLE
Allow users to request role assignment

### ISSUE THREAD

**Issue by wrenhunter** [strongdm/accessbot#66]
**Is your feature request related to a problem? Please describe.**
Corvesta has said that in some cases, users need to get access to multiple resources at once. Requesting access one at a time is tiresome, even with auto-approval. They ask if we can allow users to request Role assignment, i.e. `assign me to role OnCall2021`

**Describe the solution you'd like**
Add a new command, e.g. `assign me to role`

**Describe alternatives you've considered**
Dynamic Grants might be an alternative, after they are GA.

**Comment by camposer** [comment]
For simplicity sake, as we do with the access command, I'll follow the pattern: `assign role Xxx`

**Comment by camposer** [comment]
By default, I'll use a manual approval flow and then we can add a flag for auto-approve

**Comment by camposer** [comment]
Changing the semantics of the command to: `access to role RoleName` because in reality we'll grant temporary access to all resources listed in a role

**Comment by camposer** [comment]
I have added a `show available roles` command. It just lists all roles, in the future we might want to add more information (e.g. resources) or support a hide-roles flag

**Comment by camposer** [comment]
Besides, because some clients might want to disable `access to role role-name` or `show available roles` I added a new variable: `SDM_COMMANDS_ENABLED`. See `docs/CONFIGURE_ACCESSBOT.md`
