### ISSUE TITLE
permission fall back to default workflow after number of successful auto approval requests exhausted for a given period

### ISSUE THREAD

**Issue by tarunptala** [strongdm/accessbot#67]
Currently, after enabling `auto approval` number of requests from users are expected to grow and users may end up requests more number of times than they might actually nee. 

The idea here is not to promote the auto approval request from users unless it is absolutely necessary. Hence, we would like to limit auto approval requests for a given period of time. 

**Example** - say `user` can grant him/her self an automatic access 10 times a week before falling back to default manual approval workflow.

**Comment by camposer** [comment]
Hi @tarunptala, we're currently planning the following implementation: 

There are going to be 2 new variables: `MAX_AUTO_APPROVE_USES` and `MAX_AUTO_APPROVE_INTERVAL`.

When set, we'll keep count of every automatic approval by user. When a user reaches `MAX_AUTO_APPROVE_USES` following access requests are gonna have to be manually processed (default flow).

On every auto-approve, we'll inform the user about the number of remaining auto-approves.

The admin could use: `plugins info AccessBot` to see the number of auto-approves available per user. If a user is not present in the list, that means that there are no auto-approve requests registered for that `MAX_AUTO_APPROVE_INTERVAL`.

Every `MAX_AUTO_APPROVE_INTERVAL`, for example: every 24*60 minutes (a day) a process is going to reset all counters.

Do you think the commented functionality would solve your use case?

**Comment by tarunptala** [comment]
This sounds looks like a plan @camposer Thanks for picking this up.
