### ISSUE TITLE
Interpret hide-resource value correctly

### ISSUE THREAD

**Issue by mdube667** [strongdm/accessbot#83]
**Describe the bug**
Right now, if the tag hide-resource is set to anything, the resource will be hidden. ie: even if it's set to false

**To Reproduce**
Set tag hide-resource to false, the resource will be hidden from accessbot

**Expected behavior**
If hide-resource isn't true, the resource shouldn't be hidden.

**Comment by camposer** [comment]
Now, any value different than `false` (ignoring casing), would be interpreted as `true`. For example:

* `hide-resource=` => true
* `hide-resource=true` => true
* `hide-resource=whatever` => true
* `hide-resource=FALSE` => false
* `hide-resource=fAlSe` => false
