### ISSUE TITLE
Not able to Send Messages of Dedicated Slack Admin Channel. "sdm_admins_channel"

### ISSUE THREAD

**Issue by hjdesai2** [strongdm/accessbot#95]
**Describe the bug**

In my configuration, I am setting `sdm_admins_channel: '#platform-access-requests'`
However, Access bot is not able to recognize the admin channel name where all approval messages should ideally go based on configuration & shoots a log  `No channel named platform-access-requests exists` 

NOTE: Channel is present and Bot has all permissions & even added to that channel.

 **To Reproduce**
1.   Just set your `sdm_admins_channel` config.
2.  Try to request an approval for any role or resource. It won't shoot anything on configured admin channel.

**Expected behavior**
Ideal expectations is to get approval message on slack channel.

**Screenshots**
No messages on admin slack channel, but I get personal notifications by Platform Access Bot
<img width="496" alt="Screen Shot 2021-08-18 at 1 19 55 PM" src="https://user-images.githubusercontent.com/5409373/129966567-22dfd365-f409-4b23-8d8d-18db31b4fdea.png">

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser : chrome 
 - Version : latest version on chrome & Big Sur iOS version.

**Comment by camposer** [comment]
Hi @hjdesai2 

Thanks for reaching out, could you please specify which version of accessbot you're using?

If you're using version `1.0.x` the problem might be related to the type of channel. Is `#platform-access-requests` a private channel? In that case, please try to add the sope: `usergroups:read` to your bot. That's a typical issue documented [here](https://github.com/strongdm/accessbot/blob/main/docs/FAQ.md#how-can-i-use-accessbot-in-a-private-channel)

Side note: It might be just a typo, but keep in mind that the variable name should be all capital case and passed at startup time to your docker container. Instead of `sdm_admins_channel` it should be `SDM_ADMINS_CHANNEL`.

If the error persists, could you please provide the output of the following command sent in a DM to  `PlatformAccessBot`: `plugin config AccessBot`?

**Comment by hjdesai2** [comment]
Hello @camposer ,

I am using `accessbot version v1.1.0`  & `#platform-access-requests` is not a private channel.

In addition, I have set the Environment Variable in Uppercase , as seen in below screenshot.

NOTE: Below is screenshot of my K8s Deployment file 

<img width="578" alt="Screen Shot 2021-08-18 at 11 03 17 PM" src="https://user-images.githubusercontent.com/5409373/130016229-6656c11d-66ba-4fd2-8c19-c981d7229312.png">


Attaching screenshot for  `plugin config AccessBot`

![Screen Shot 2021-08-18 at 11 12 15 PM](https://user-images.githubusercontent.com/5409373/130017211-e98b03fc-058e-4c4c-b567-5c413e8b8590.png)

**Comment by camposer** [comment]
Hi @hjdesai2 

Thank you very much for your quick reply! Definitively we'll need to investigate this. We've seen some problems with the new version (`1.1`) when there are many users or channels on a Slack Org.

A little bit of context, version 1.1.x uses the new Slack API (Bolt). Version 1.0.x uses the old Slack API (RTM). We've battle tested RTM, but Bolt is still being tested.

Could you please try to use version 1.0.x? In that case, you'll need to create a classic app. All code and docs live in this repo in a separate branch:
* [Index](https://github.com/strongdm/accessbot/tree/1.0.x)
* [Configure Slack Classic App](https://github.com/strongdm/accessbot/blob/1.0.x/docs/CONFIGURE_SLACK.md). It follows a different installation process. IMPORTANT: You need only one token, and it has a different name, just: `SLACK_TOKEN`.
* [Latest Release 1.0.4](https://github.com/strongdm/accessbot/releases/tag/1.0.4)

**Comment by camposer** [comment]
There are many things that can be causing this problem. We're currently trying to setup a large Slack Organization so we can test properly v1.1.x. Besides, some changes has been made into the Bolt Backend. 

I'll create 2 new issues and refer them here.
1. Setup testing organization
2. Introduce pagination in Bolt Backend functions for getting users and channels

**Comment by camposer** [comment]
We've finished #108 and #109. The next step is to generate a new release, once we do that, we'll close this bug.

**Comment by camposer** [comment]
Here's the release: https://github.com/strongdm/accessbot/releases/tag/1.1.2
